# Generated by Django 4.1.6 on 2023-02-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Non-Technical', 'Non-Technical')], max_length=50, null=True),
        ),
    ]
