# Generated by Django 4.1.6 on 2023-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
