# Generated by Django 4.1.6 on 2023-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_registration_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Webinar', 'Webinar')], max_length=50, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='preview_images')),
                ('preview', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(null=True)),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
