# Generated by Django 4.1.6 on 2023-02-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_no',
        ),
    ]
